version: '3.8'

services:
  frontend:
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./nextjs/.env.local
    depends_on:
      - backend

  backend:
    build:
      context: ./python/flask_app
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    env_file:
      - ./python/flask_app/.env
    environment:
      BACKEND_URL: http://backend:8050

    volumes:
      - ./python/flask_app:/usr/src/app

networks:
  default:
    name: app_network
