#!/bin/sh
cd code/nextjs || exit 1

echo "Checking for changes in code/nextjs..."

# Check if there are any changes in the current folder
if git diff --quiet HEAD -- .; then
  echo "No changes detected in code/nextjs. Exiting..."
  exit 0
fi

echo "Running Prettier..."
# Format files and stage changes
npx prettier --write .

echo "Staging changes..."
git add .
