name: Next.js CI

on:
  pull_request:
    branches:
      - '*'
    paths:
      - 'code/nextjs/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./code/nextjs
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.17.0

    - name: Install Dependencies
      run: npm install

    - name: Set Environment Variables (figure out removing this)
      run: |
        echo "MONGODB_URI=PLACEHOLDER" >> $GITHUB_ENV
        echo "MONGODB_DB=PLACEHOLDER" >> $GITHUB_ENV

    - name: Build Next.js Application
      run: npm run build

    # TODO: add tests!
    # - name: Run Tests
    #   run: npm test
