name: Build & Deploy to ECR

on:
  push:
    branches: [ "main" ]  # or whichever branch you want to trigger on
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}:$GITHUB_SHA code/python/flask_app

      - name: Push to ECR
        run: |
          # Optionally tag as 'latest' in addition to using the commit SHA
          docker tag ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}:$GITHUB_SHA \
                     ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}:latest

          docker push ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}:$GITHUB_SHA
          docker push ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}:latest
