name: Build and Push backend to ECR and Deploy to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the Docker image to ECR
      - name: Build and Push Docker Image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.BACKEND_ECR_REPOSITORY_NAME }}
          IMAGE_TAG: "latest"
        run: |
          # Define the full image name
          IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          # Build the Docker image
          docker build -t "$IMAGE_URI" ./code/python/flask_app

          # Push the Docker image to ECR
          docker push "$IMAGE_URI"
